@baseurl = http://localhost:3000

@employee = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZDkyOGM5MS1kNTQwLTRjNDQtYjVkZC03Y2NiYzA3ZWZmMjAiLCJlbWFpbCI6ImZ1bmNpb25hcmlvLnRlc3RlMkBlbXByZXNhLmNvbSIsInJvbGUiOiJFTVBMT1lFRSIsImlhdCI6MTc3MjkxMDEyNiwiZXhwIjoxNzczNTE0OTI2LCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.DfziC8OBruwTTGNbvYZPDdj2uTrfdZ6JyWiaMc-9o-Y

@admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODVlZDg5Yi04NTg2LTQxNzUtYmNiNC00ZjQ3YjQ5ZGJiOWUiLCJlbWFpbCI6ImphZHNvbi50ZXN0ZUBlbXByZXNhLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MjkxMDIwNiwiZXhwIjoxNzczNTE1MDA2LCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.nMmyXNp7kGazEFvcFFLRrhljxxsnhYWzOjsiQw14LIQ

@tecnico = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YWI2M2M1MC05OTI2LTRhNzYtYjFjYy1mYmIzZjYzNTFiMjQiLCJlbWFpbCI6InRlY25pY28udGVzdGVAZW1wcmVzYS5jb20iLCJyb2xlIjoiVEVDSE5JQ0lBTiIsImlhdCI6MTc3MjkxMDI3MCwiZXhwIjoxNzczNTE1MDcwLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.EPuLvQmCsiYpE9Q4gcJyjdoROIAZvzk4ixSflLw33yc

@userId = bd928c91-d540-4c44-b5dd-7ccbc07eff20

@ticketId = a1cf9a3b-1c54-4731-a59a-3d00ee87b18f

@messageId =

### Authenticate / login
POST {{baseurl}}/auth/login?offset=10&limit=10&order=DESC
Content-Type: application/json

{
  "email": "tecnico.teste2@empresa.com",
  "password": "123456"
}

### Users

### List users (requires JWT)
GET {{baseurl}}/users
Authorization: Bearer {{employee}}

### Get a single user
GET {{baseurl}}/users/{{userId}}
Authorization: Bearer {{tecnico}}

### Create user
POST {{baseurl}}/users
Authorization: Bearer {{admin}}
Content-Type: application/json

{
  "name": "Funcionário Teste",
  "email": "tecnico.teste3@empresa.com",
  "password": "123456",
  "role": "TECHNICIAN"
}

### Update user
PATCH {{baseurl}}/users/{{userId}}
Authorization: Bearer {{}}
Content-Type: application/json

{
  "name": "",
  "email": ""
}

### Delete user
DELETE {{baseurl}}/users/{{userId}}
Authorization: Bearer {{}}

### Tickets

# Create ticket
POST {{baseurl}}/tickets
Authorization: Bearer {{employee}}
Content-Type: application/json

{
  "title": "Preciso de ajuda",
  "description": "Estou com problemas para acessar o sistema."
}

### List tickets
GET {{baseurl}}/tickets
Authorization: Bearer {{tecnico}}

### Get ticket by id
GET {{baseurl}}/tickets/{{ticketId}}
Authorization: Bearer {{}}

# Update ticket priority
PATCH {{baseurl}}/tickets/{{ticketId}}/priority
Authorization: Bearer {{}}
Content-Type: application/json

{
  "priority": ""
}

### Update ticket assigned
PATCH {{baseurl}}/tickets/{{ticketId}}/assigned
Authorization: Bearer {{tecnico}}

### Update ticket status
PATCH {{baseurl}}/tickets/{{ticketId}}/status
Authorization: Bearer {{}}
Content-Type: application/json

{
  "status": ""
}

### Update Diagnoses
PATCH {{baseurl}}/tickets/{{ticketId}}/diagnosis
Authorization: Bearer {{admin}}
Content-Type: application/json

{
  "diagnosis": "Alarme Falso"
}

### Delete ticket
DELETE {{baseurl}}/tickets/{{ticketId}}
Authorization: Bearer {{}}

### Messages

### Create message
POST {{baseurl}}/messages
Authorization: Bearer {{employee}}
Content-Type: application/json

{
  "content": "Você pode vir a minha mesa?",
  "ticketId": "{{ticketId}}"
}

### List messages
GET {{baseurl}}/messages/a1cf9a3b-1c54-4731-a59a-3d00ee87b18f
Authorization: Bearer {{admin}}

